{"asctime": "2021-08-24 01:56:50,549", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-24 01:56:50,549", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-24 02:08:45,551", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-24 02:08:45,551", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-24 02:08:45,552", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :'str' object is not callable"}
{"asctime": "2021-08-24 02:10:19,747", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-24 02:10:19,748", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-24 02:12:56,997", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :'str' object is not callable"}
{"asctime": "2021-08-24 02:13:01,949", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-24 02:13:01,949", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-24 02:13:10,461", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :Class 'builtins.str' is not mapped"}
{"asctime": "2021-08-24 12:49:44,274", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-24 12:49:44,275", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 05:35:07,944", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :cannot convert dictionary update sequence element #0 to a sequence"}
{"asctime": "2021-08-25 05:35:57,945", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :cannot convert dictionary update sequence element #0 to a sequence"}
{"asctime": "2021-08-25 05:36:48,212", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'list' object has no attribute 'dict'"}
{"asctime": "2021-08-25 05:38:05,228", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 05:40:42,811", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object has no attribute 'data'"}
{"asctime": "2021-08-25 05:41:18,427", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object has no attribute 'data'"}
{"asctime": "2021-08-25 05:41:47,977", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object has no attribute 'data'"}
{"asctime": "2021-08-25 05:42:19,682", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Query' object is not callable"}
{"asctime": "2021-08-25 05:42:44,797", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :object of type 'Chains' has no len()"}
{"asctime": "2021-08-25 05:44:32,795", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 05:45:12,038", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object has no attribute 'dict'"}
{"asctime": "2021-08-25 05:45:50,114", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 05:46:44,022", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 05:53:44,452", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 05:54:25,680", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :cannot convert dictionary update sequence element #0 to a sequence"}
{"asctime": "2021-08-25 05:55:57,802", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'list' object has no attribute 'items'"}
{"asctime": "2021-08-25 05:57:38,019", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object has no attribute 'items'"}
{"asctime": "2021-08-25 05:57:53,415", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 05:58:27,237", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :list index out of range"}
{"asctime": "2021-08-25 05:58:28,668", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :list index out of range"}
{"asctime": "2021-08-25 05:59:15,056", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :list index out of range"}
{"asctime": "2021-08-25 06:02:16,398", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 06:02:37,841", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 06:03:01,672", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Locations' object is not iterable"}
{"asctime": "2021-08-25 06:03:21,297", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'list' object has no attribute 'update'"}
{"asctime": "2021-08-25 06:03:51,363", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'list' object has no attribute 'update'"}
{"asctime": "2021-08-25 06:05:24,544", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 06:05:52,623", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :cannot convert dictionary update sequence element #0 to a sequence"}
{"asctime": "2021-08-25 06:12:04,842", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :cannot convert dictionary update sequence element #0 to a sequence"}
{"asctime": "2021-08-25 06:17:42,824", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :object of type 'Chains' has no len()"}
{"asctime": "2021-08-25 06:31:13,399", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 06:38:42,392", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 06:39:56,578", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 06:57:39,026", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 06:58:35,816", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 06:59:51,320", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 07:11:18,189", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 07:12:01,461", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
{"asctime": "2021-08-25 07:13:26,267", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:13:47,018", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :Class ''chains'' is not mapped"}
{"asctime": "2021-08-25 07:14:11,782", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:14:21,219", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 07:19:01,619", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:19:09,519", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :bulk_insert_mappings() missing 1 required positional argument: 'mappings'"}
{"asctime": "2021-08-25 07:19:34,686", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:19:48,556", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :Class 'builtins.NoneType' is not mapped"}
{"asctime": "2021-08-25 07:22:46,051", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:23:44,451", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Bakers) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s)]\n[parameters: ({'name': 'Bakers', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}, {'name': \"Macy's\", 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'no'})]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 07:24:26,500", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:24:26,527", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Bakers) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s)]\n[parameters: ({'name': 'Bakers', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}, {'name': \"Macy's\", 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'no'})]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 07:31:42,470", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:31:42,500", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :Class 'builtins.NoneType' is not mapped"}
{"asctime": "2021-08-25 07:31:50,143", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:32:00,411", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Armani) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s) RETURNING chains.id]\n[parameters: {'name': 'Armani', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 07:32:28,237", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:34:54,657", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Armani) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s) RETURNING chains.id]\n[parameters: {'name': 'Armani', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 07:43:16,658", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:43:33,271", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :Class 'builtins.NoneType' is not mapped"}
{"asctime": "2021-08-25 07:44:21,984", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:45:12,230", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:45:45,450", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Armani) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s) RETURNING chains.id]\n[parameters: {'name': 'Armani', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 07:45:59,827", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:46:24,890", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :'Chains' object is not iterable"}
{"asctime": "2021-08-25 07:46:48,377", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 07:46:53,653", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Armani) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s) RETURNING chains.id]\n[parameters: {'name': 'Armani', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 07:47:37,398", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 11:44:07,054", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 11:44:07,055", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:44:07,061", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Armani) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s) RETURNING chains.id]\n[parameters: {'name': 'Armani', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 11:47:58,118", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "create record in for chains"}
{"asctime": "2021-08-25 11:47:58,118", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:47:58,118", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChains"}
{"asctime": "2021-08-25 11:50:32,154", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 11:50:32,155", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:50:59,258", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 11:50:59,258", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:50:59,265", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Bakers) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s) RETURNING chains.id]\n[parameters: {'name': 'Bakers', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 11:51:11,009", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 11:51:11,009", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:52:09,130", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 11:52:09,130", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:56:50,583", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 11:56:50,584", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:57:53,921", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 11:57:53,921", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:59:02,821", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 11:59:02,822", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:59:02,822", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChains"}
{"asctime": "2021-08-25 11:59:07,987", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 11:59:07,988", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 11:59:07,988", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChains"}
{"asctime": "2021-08-25 12:03:13,569", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:03:13,569", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:03:13,569", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChains"}
{"asctime": "2021-08-25 12:03:34,666", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:03:34,666", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:09:43,574", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:09:43,574", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:09:43,574", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChains"}
{"asctime": "2021-08-25 12:12:32,070", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:12:32,070", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:12:32,070", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChains"}
{"asctime": "2021-08-25 12:13:09,994", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:13:09,994", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:16:49,257", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:16:49,257", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:19:10,457", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:19:10,457", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:19:10,457", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChains"}
{"asctime": "2021-08-25 12:21:48,213", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:21:48,213", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:21:48,219", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"chains_name_key\"\nDETAIL:  Key (name)=(Bakers) already exists.\n\n[SQL: INSERT INTO chains (name, image_url, country, online_store) VALUES (%(name)s, %(image_url)s, %(country)s, %(online_store)s) RETURNING chains.id]\n[parameters: {'name': 'Bakers', 'image_url': 'http://imghost.com/2.jpg', 'country': 'US', 'online_store': 'yes'}]\n(Background on this error at: http://sqlalche.me/e/gkpj)"}
{"asctime": "2021-08-25 12:21:56,836", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:21:56,836", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:25:28,317", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 12:25:28,317", "namespace": "service_dataset", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 12:25:28,317", "namespace": "service_dataset", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChains"}
{"asctime": "2021-08-25 12:46:03,909", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "No records found for chain : kxc"}
{"asctime": "2021-08-25 13:11:20,099", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "No records found for chain : Bakers"}
{"asctime": "2021-08-25 13:11:20,102", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 13:11:20,102", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 14:51:50,581", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 14:51:50,581", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 14:51:50,582", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "Error while inserting records in chains :DeclarativeMeta object argument after ** must be a mapping, not CreateChain"}
{"asctime": "2021-08-25 14:53:27,088", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 14:53:28,887", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 14:55:52,346", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 14:55:52,347", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 14:57:48,399", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 14:57:48,910", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 15:16:53,008", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :Use params or add_pagination"}
{"asctime": "2021-08-25 15:18:09,357", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :unhashable type: 'slice'"}
{"asctime": "2021-08-25 15:19:54,066", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :Use params or add_pagination"}
{"asctime": "2021-08-25 15:23:39,403", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :'list' object has no attribute '__dict__'"}
{"asctime": "2021-08-25 15:32:58,630", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "Error while fetching records in chains :Use params or add_pagination"}
{"asctime": "2021-08-25 15:42:36,391", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Insert record for single chains"}
{"asctime": "2021-08-25 15:42:36,391", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Inserting records in chains"}
{"asctime": "2021-08-25 15:47:34,396", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "No records found for chain : Bakers"}
{"asctime": "2021-08-25 15:47:52,539", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "No records found for chain : Bakers"}
{"asctime": "2021-08-25 15:48:23,655", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "ERROR", "message": "No records found for chain : Bakers"}
{"asctime": "2021-08-25 23:24:45,028", "namespace": "python_eng_exercise", "sub_name": "crud", "level": "INFO", "message": "Inserting records in locations"}
